# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "66226487e44484fa62dd83d19f756fe5"
name = "discount-test"
handle = "discount-test-110"
application_url = "https://sink-yen-plug-tunisia.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "evolution-app-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,write_discounts_allocator_functions,write_products"

[auth]
redirect_urls = [
  "https://sink-yen-plug-tunisia.trycloudflare.com/auth/callback",
  "https://sink-yen-plug-tunisia.trycloudflare.com/auth/shopify/callback",
  "https://sink-yen-plug-tunisia.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
